{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-operator-metrics-reader
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
