apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aerospike-kubernetes-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: ":{{ .Values.healthPort | default 8081 }}"
    metrics:
      bindAddress: "127.0.0.1:{{ .Values.metricsPort | default 8080 }}"
    webhook:
      port: {{ .Values.webhookServicePort | default 9443 }}
    leaderElection:
      leaderElect: true
      resourceName: 96242fdf.aerospike.com
